graphite:
  host: localhost
  port: 2003

---

spring:
  zipkin:
    baseUrl: http://localhost:8070/
  sleuth:
    sampler:
      percentage: 1.0
    log:
      json:
        enabled: true

---

spring:
  rabbitmq:
    host: localhost
    port: 5672
