server:
  port: 0

message: My new message from Config Server

management:
  shell:
    auth:
      simple:
        user:
          name: admin
          password: pass

---

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: newReservations
          group: reservations
          durableSubscription: true
